spring:
  datasource:
    url: jdbc:postgresql://dpg-cql2ri3qf0us73bt0980-a/school_site_gajv
    username: school_site_gajv_user
    password: HuxKdWQ37bhUT91uTAkfK85xbHz27uPf
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

file:
  upload:
    directory: ${FILE_UPLOAD_DIRECTORY:/src/main/resources/static}

# File Upload Configuration
spring.servlet.multipart:
  max-file-size: 100MB
  max-request-size: 100MB


